#!/bin/bash

NUMBER=$1
OP=$2

if [[ $OP == "stop" ]];then
    docker ps -a | grep social-spide | awk '{ print $1 }' |xargs docker rm -f;
    exit 0
fi

if [[ $OP != "start" ]];then
    echo "operation : [start/stop]"
    exit 0
fi

res="$(cat << EOF | python
import os
print(os.getcwd())
SERVERS=[]
if os.path.exists("SERVERS"):
    with open("SERVERS") as fp:
        for l in fp:
            if l.strip():
                s,sp,p = l.split(":")
                SERVERS.append([s,sp,p])
for i in range($NUMBER):
    s,sp,p = SERVERS[i% len(SERVERS)]
    print("docker run -dp " + str(9000+ i) + ":8080  -e SHADOW_HOST={s} -e SHADOW_PORT={sp} -e SHADOW_PASS={p} -e PORT=8080 social-spide;".format(s=s,sp=sp,p=p))

EOF)"


echo "solder ready!!!";

eval $res
echo "solder running"

